### ISSUE TITLE
报错 bootstrap.min.js:6Uncaught Error: Bootstrap's JavaScript requires jQuery 怎么解决

### ISSUE THREAD

**Issue by tomgets85** [jiyis/register#3]
报错 bootstrap.min.js:6Uncaught Error: Bootstrap's JavaScript requires jQuery 怎么解决

**Comment by tomgets85** [comment]
找到原因了，把 gulpfile.js的 
    gulp.src("vendor/bower_dl/AdminLTE/plugins/jQuery/_.js").pipe(rename('jquery.min.js'))
        .pipe(gulp.dest("resources/assets/js/"));
改为
    gulp.src("vendor/bower_dl/AdminLTE/plugins/jQuery/_.js")
        .pipe(gulp.dest("resources/assets/js/"));
即可

**Comment by jiyis** [comment]
这个AdminLte如果更新jquery的话会导致版本号不对，应该是下面合并jquery的时候我带上了版本号的问题！ 建议在bower.json中依赖指定版本
